services:
  - type: web
    name: journalapp
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/journalApp-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080